name: Build C

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Create Build Directory
      run: mkdir build

    - name: Build MsCtfMonitor DLL
      working-directory: ${{ github.workspace }}
      run: |
        cl.exe Exploit/MsCtfMonitor.c /LD /Fe:build/MsCtfMonitor.dll

    - name: Build Exploit
      working-directory: ${{ github.workspace }}
      run: |
        cl.exe Exploit/exploit.c /Fe:build/exploit.exe shell32.lib user32.lib advapi32.lib dbghelp.lib


    - name: Verify Build
      run: |
        if (Test-Path "build\MsCtfMonitor.dll") {
            Write-Host "MsCtfMonitor.dll built successfully"
        } else {
            Write-Error "MsCtfMonitor.dll build failed"
            exit 1
        }
        if (Test-Path "build\exploit.exe") {
            Write-Host "exploit.exe built successfully"
        } else {
            Write-Error "exploit.exe build failed"
            exit 1
        }

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CVE-2024-6769-exploit
        path: |
          build/MsCtfMonitor.dll
          build/exploit.exe
          README.md
          screenshot-high.png
          screenshot-medium-plus.png

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/MsCtfMonitor.dll
          build/exploit.exe
          README.md
          screenshot-high.png
          screenshot-medium-plus.png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List Build Directory
      run: |
        dir build
